#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';
$config = include_once __DIR__ . '/app/Config/App.php';

use Minicli\App;

$config = array_merge(
    ['app_path' => __DIR__ . '/app/Command'],
    $config
);

$app = new App($config);

$app->setSignature("Figgebot for Twitch.\n./minicli twitch");
$app->runCommand($argv);
